# Default Service Peek Configuration
# This configuration is built into the Docker image and used when no custom config is provided

# Server configuration
server:
  port: 3001
  host: "0.0.0.0"  # Bind to all interfaces in container

# Client configuration  
client:
  port: 8080
  host: "0.0.0.0"  # Bind to all interfaces in container
  api_url: "http://localhost:3001/api/v1"

# Database configuration
database:
  path: "/app/data/database/opsimate.db"  # Container path

# Security configuration
security:
  private_keys_path: "/app/data/private-keys"  # Container path for SSH keys
