# Opsimate Configuration
# Simple configuration file with essential settings

# Server configuration
server:
  port: 3001  # Backend API server port
  host: "localhost"  # Use "0.0.0.0" for Docker

# Client configuration  
client:
  port: 8080  # Frontend development server port
  api_url: "http://localhost:3001/api/v1"  # Backend API URL

# Database configuration
database:
  path: "/Users/idanlodzki/code/windsurf_projects/OpsiMate/apps/server/data/OpsiMate.db2"  # SQLite database file path

# Security configuration
security:
  private_keys_path: "/Users/idanlodzki/code/windsurf_projects/OpsiMate/apps/server/data/private-keys"  # SSH private keys directory
