# Service Peek Configuration for Docker Container
# Container-specific configuration with proper paths

# Server configuration
server:
  port: 3001
  host: "0.0.0.0"  # Bind to all interfaces in container
  api_base_path: "/api/v1"
  cors:
    origin: "*"
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization"]

# Client configuration
client:
  port: 8080
  host: "0.0.0.0"  # Bind to all interfaces in container
  api_url: "http://localhost:3001/api/v1"

# Database configuration
database:
  path: "/app/data/database/service_peek.db"  # Container path for database

# Security configuration
security:
  private_keys_path: "/app/data/private-keys"  # Container path for SSH keys

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "console"
