# Custom Docker Configuration for Service Peek
# This demonstrates mounting a custom config file

# Server configuration
server:
  port: 3001
  host: "0.0.0.0"  # Bind to all interfaces in container

# Client configuration  
client:
  port: 8080
  host: "0.0.0.0"  # Bind to all interfaces in container
  api_url: "http://localhost:3001/api/v1"

# Database configuration
database:
  path: "/app/data/database/service_peek_custom.db"  # Custom database name

# Security configuration
security:
  private_keys_path: "/app/data/private-keys"  # Container path for SSH keys

# Logging configuration
logging:
  level: "info"
  format: "json"
  
# Custom settings for demonstration
custom:
  environment: "docker-custom"
  description: "This is a custom configuration file mounted as a volume"
